### ISSUE TITLE
Parsing variable values

### ISSUE THREAD

**Issue by odero** [graphql-dotnet/parser#82]
Parsed variable values come in as literals without any associated GraphQLtypes

Example:
If I've defined a variables as  `{username: "peterhouse"}`
and defined a query as
```graphql
query($username: String) {
  Person(uname: $username, firstName: "Pete") {
    id, email
  }
}
```
1. What is the best way to parse everything i.e. query + variable definitions. Variable definition in this case being `{username: "peterhouse"}`. I'm not seeing any examples on how to do this - not even in the tests. 
2. What's the prescribed way for retrieving the value of a variable as a `GraphQLType`  i.e. same way the parser returns `firstName` above as a `GraphQLType` with `ASTNodeKind` as StringValue?

**Comment by sungam3r** [comment]
I hope this picture will help
![изображение](https://user-images.githubusercontent.com/21261007/95655864-00c31080-0b13-11eb-9c35-24746224dbca.png)

**Comment by sungam3r** [comment]
> What is the best way to parse everything i.e. query + variable definitions. Variable definition in this case being {username: "peterhouse"}. I'm not seeing any examples on how to do this - not even in the tests.

Variables exist and are passed separately from the query text. They are represented by json object. You can see how this happens in https://github.com/graphql-dotnet/graphql-dotnet or https://github.com/graphql-dotnet/server projects. The parser is used as the foundation for parsing the query, but additional steps still need to be taken in order to organize the high-level execution of the query.

**Comment by Shane32** [comment]
Unfortunately the exact format of variables are not covered by the graphql specification, other than a requirement that they can be coerced into the graph types they represent.  So for example it is theoretically possible to utilize a binary transport that passes dates in a native format rather than a string.

**Comment by sungam3r** [comment]
Closed as answered.
